### ISSUE TITLE
ConfigMap Watcher got nil Event

### ISSUE THREAD

**Issue by lxs137** [tumblr/k8s-sidecar-injector#15]
# What's going on?

Injector deployment crash frequently. I got crash log:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xef548b]

goroutine 35 [running]:
github.com/tumblr/k8s-sidecar-injector/internal/pkg/config/watcher.(*K8sConfigMapWatcher).Watch(0xc0002cca00, 0x12d1f60, 0xc0002d8600, 0xc000300600, 0x0, 0x0)
	/src/internal/pkg/config/watcher/watcher.go:109 +0x36b
main.main.func1.1(0xc0002cca00, 0x12d1f60, 0xc0002d8600, 0xc000300600)
	/src/cmd/main.go:114 +0x77
created by main.main.func1
	/src/cmd/main.go:111 +0xd7
```
 I think it just because watcher got a Event with a `nil Object` and try to use it. I find this bug is caused by https://github.com/kubernetes/client-go/issues/334

# Expected Behavior

# Reproducer

can reproduce with any valid sidecar configurations, just wait a few minutes

# Version Deets

* Kubernetes Version: `v1.13.3`
* `k8s-sidecar-injector` Version: `release-v0.1.6`

**Comment by byxorna** [comment]
@lxs137 thanks for the bug report! This is interesting - we have not seen this behavior internally. Regardless, we will get this fixed up for you!
