### ISSUE TITLE
Status annotation ignores custom annotation namespace

### ISSUE THREAD

**Issue by noahgoldman** [tumblr/k8s-sidecar-injector#20]
# What's going on?

Setting a custom annotation namespace `-annotation-namespace` does not effect the `injector.tumblr.com/status` annotation.

The root cause seems quite clear from reading the source.  The `/status` annotation is set in [webhook.go#L462](https://github.com/tumblr/k8s-sidecar-injector/blob/master/pkg/server/webhook.go#L462), using the [config.InjectionStatusAnnotation](https://github.com/tumblr/k8s-sidecar-injector/blob/master/internal/pkg/config/config.go#L24) package-level variable.  This variable is hardcoded to use `annotationNamespaceDefault`, which is set to `"injector.tumblr.com"`.  This pretty clearly explains why the user-specified configuration is ignored.

Interestingly, both `/request` and `/status` are properly formatted using `AnnotationNamespace` in [(*WebhookServer).getSidecarConfigurationRequested](https://github.com/tumblr/k8s-sidecar-injector/blob/master/pkg/server/webhook.go#L142).  Seems like that configuration format just needs to be used in both places.

# Expected Behavior

Setting `-annotation-namespace=sidecar-injector.eks.qcinternal.io` should cause Pods with injected sidecars to have the annotation `sidecar-injector.eks.qcinternal.io/status: injected`.  Instead, we see `injector.tumblr.com/status: injected`.  The annotation setting which sidecar configuration to use is `sidecar-injector.eks.qcinternal.io/request`.

# Reproducer

The injector is launched with the following arguments:

```
    - --v
    - "2"
    - --tls-cert-file
    - /var/lib/tls-cert/tls.crt
    - --tls-key-file
    - /var/lib/tls-cert/tls.key
    - --annotation-namespace
    - sidecar-injector.eks.qcinternal.io
    - --configmap-labels
    - app.kubernetes.io/instance=k8s-sidecar-injector-batch-production-blue,app.kubernetes.io/component=sidecar-config
```

I'm going to omit sidecar configurations in particular, as the root cause seems quite obvious and the configurations are for internal tools.  I can provide similar information if necessary.

# Version Deets

* Kubernetes Version: `v1.13.8`
* k8s-sidecar-injector Version: `v0.1.7`

**Comment by byxorna** [comment]
@noahgoldman thanks for this issue! Great catch - I definitely missed this while making the injector more modular. Let me see if i can get a quick PR up for you.

More info shortly!

**Comment by byxorna** [comment]
@noahgoldman can you check out the `:latest` build now? Hopefully this is fixed :)
