### ISSUE TITLE
serviceMonitor error

### ISSUE THREAD

**Issue by zhangjianweibj** [tumblr/k8s-sidecar-injector#23]
hello,
i create injector with the document /docs/deployment.md step by setp and everything is ok except operation:kubectl create -f service-monitor.yaml.
is anything forget?

error: unable to recognize "service-monitor.yaml": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"

**Comment by byxorna** [comment]
Hi @zhangjianweibj. `ServiceMonitor` resources depend on https://github.com/coreos/prometheus-operator being deployed - if you do not use the Prometheus Operator, you can just skip the ServiceMonitor without worry!

**Comment by zhangjianweibj** [comment]
ok.very thanks.
