### ISSUE TITLE
Default injection for all new containers?

### ISSUE THREAD

**Issue by kandeshvari** [tumblr/k8s-sidecar-injector#38]
Does k8s-sidecar-injector has default injection support for _all_ creating containers?

It would be convenient to add cluster-wide envs to all pods

**Comment by byxorna** [comment]
Hi @kandeshvari 
No, the sidecar injector does not support injection for all pods. You must explicitly tell the sidecar injector which configuration to use when launching a pod, by launching the pod with the appropriate annotation. 

Internally, we have addressed this need by explicitly adding the annotation asking for cluster-wide env vars wherever they are needed.

**Comment by kandeshvari** [comment]
@byxorna thank you for answer. Looks like I'll use your solution.
