### ISSUE TITLE
add support for initContainers

### ISSUE THREAD

**Issue by byxorna** [tumblr/k8s-sidecar-injector#7]
# What's going on?

We should support initContainers in our injection configs

https://github.com/tumblr/k8s-sidecar-injector/pull/9 and https://github.com/tumblr/k8s-sidecar-injector/pull/8 address this

**Comment by komapa** [comment]
I thought initContainers cannot be injected?

**Comment by byxorna** [comment]
@komapa i am going to reinvestigate when i have time, and confirm. it would be great if we could; if not, ill have links here explaining exactly why they cant be patched into a pod.

**Comment by iwilltry42** [comment]
@komapa I couldn't find any resource regarding your concerns. Only a wrong order of admission controllers might prevent injecting containers, e.g. PodSecurityPolicies (but containers in general, not only initContainers). 
Anyways I can confirm for [#8](https://github.com/tumblr/k8s-sidecar-injector/pull/8), that it works.
I tested it on Minikube and in our development cluster (though we don't have stuff like PodSecurityPolicies there).

**Comment by byxorna** [comment]
@komapa @iwilltry42 I initially looked into this (way before this was opensourced) and I thought I found some reason I couldnt inject initContainers; I was clearly very mistaken :)

Thanks for sorting this out!

**Comment by byxorna** [comment]
Closed via https://github.com/tumblr/k8s-sidecar-injector/pull/8
